apiVersion: core.openfeature.dev/v1alpha2
kind: FeatureFlagConfiguration
metadata:
  name: featureflagconfiguration-sample
spec:
  featureFlagSpec:
    flags:
      foo:
        state: "ENABLED"
        variants:
          "bar": "BAR"
          "baz": "BAZ"
        defaultVariant: "baz"
        targeting: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-curl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-busybox-curl-app
  template:
      metadata:
        labels:
          app: my-busybox-curl-app
        annotations:
          openfeature.dev/enabled: "true"
          openfeature.dev/featureflagconfiguration: "default/featureflagconfiguration-sample"
      spec:
        containers:
        - name: busybox
          image: yauritux/busybox-curl:latest
          ports:
          - containerPort: 80
          args:
            - sleep
            - "30000"