{{ if eq ( include "chart.namespace" . ) .Values.defaultNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: '{{ include "chart.namespace" . }}'
{{ end }}