apiVersion: core.openfeature.dev/v1alpha1
kind: FeatureFlagConfiguration
metadata:
  name: featureflagconfiguration-sample
spec:
  flagDSpec:
    envs:
    - name: FOO
      value: BAR
  featureFlagSpec: |
    {}