name: release

on:
  push:
    tags:
      - "v*.*.*"
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0' 
      - run: |
          IMG=ghcr.io/open-feature/open-feature-operator:${{ steps.get_version.outputs.VERSION }} make release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            config/rendered/release.yaml
